### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by gorvelyfab** [project-collins/grunt-libsass#9]
by launching the task libass I have the following error message

Running "libsass:dist" (libsass) task
Segmentation fault (core dumped)

**Comment by c990802** [comment]
Same here. It seems to be related with v0.2.1 as it does not happen with the previous version.

**Comment by robotlovesyou** [comment]
This library is no longer maintained. You should switch to grunt-sass (which does the same thing but is kept up to date)

**Comment by c990802** [comment]
@robotlovesyou  wasn't aware. Thanks for letting me know.

**Comment by gorvelyfab** [comment]
@robotlovesyou  actually because I am going to have grunt-sass and everything works
